export const COLOR_STEP = 10
export const NUMBER_OF_COLORS = 16777215
export const CREATE_SHARES = 'CREATE_SHARES'
export const CHANGE_DATA_ELEMENT = 'CHANGE_DATA_ELEMENT'
export const CHANGE_ACTIVE_MODAL = 'CHANGE_ACTIVE_MODAL'